_extends: .github

repository:
  name: NucleosMenuBundle
  description: 🔗 This bundle provides services for defining static menus for symfony applications.
  homepage: https://nucleos.rocks
  topics: hacktoberfest, symfony, symfony-bundle, bundle, php, menu, knpmenu, generator, sonata, sonata-block
